### ISSUE TITLE
About training datasets

### ISSUE THREAD

**Issue by renegaderl** [mikel-brostrom/Yolov3_DeepSort_Pytorch#1]
Hi there, really appreciate ur sharing. Could u tell me what datasets u used when training the yolo in this person-only mode?

**Comment by mikel-brostrom** [comment]
Hi! Glad you liked my repo

Yolo was trained on the whole COCO dataset (https://cocodataset.org/#overview). However, at inference time all the detections not classed as persons are filtered out.

The deep association metric for deep sort was trained on the MARS datatset (http://www.liangzheng.com.cn/Project/project_mars.html)

**Comment by renegaderl** [comment]
> Hi! Glad you liked my repo
> 
> Yolo was trained on the whole COCO dataset (https://cocodataset.org/#overview). However, at inference time all the detections not classed as persons are filtered out.
> 
> The deep association metric for deep sort was trained on the MARS datatset (http://www.liangzheng.com.cn/Project/project_mars.html)

Thx! This really helps me a lot.
