### ISSUE TITLE
How to use device GPU

### ISSUE THREAD

**Issue by utsavpatel22** [mikel-brostrom/Yolov3_DeepSort_Pytorch#2]
Hello,
I wanted to use the tracker with the GPU that I have on my machine, I dont want to use the docker file. I tried providing the --device argument but it doent work. I have a single GPU machine with Nvidia GTX 1060.

**Comment by mikel-brostrom** [comment]
Hi! Thank you for showing interest in my repo!
What is the error you get?

**Comment by utsavpatel22** [comment]
I am not getting any errors, but I am not able to change the device using the argument given to track.py file. It always uses CPU. I am giving "gpu" as the argument, I am not sure if I am correct or not.

**Comment by mikel-brostrom** [comment]
The --device argument should be "cpu" or your available CUDA devices, i.e., "0", "0,1"...

But it seems to me like CUDA ([https://developer.nvidia.com/cuda-toolkit]) is not available in your environment at all. The select_device method checks whether the device argument is "cpu" or not. If not, it fetch all the CUDA available devices and use the first one as your CUDA device.

**Comment by utsavpatel22** [comment]
Thank you @mikel-brostrom for responding. The issue was with the torch version, it was not compatible with the Nvidia Drivers I have installed on my system and that's why it was not able to detect the GPU. I downgraded the torch version to 1.1.0 and torchvision version to 0.3.0. It works now! Thanks.
