### ISSUE TITLE
模型链接失效

### ISSUE THREAD

**Issue by Angel0003** [mikel-brostrom/Yolov3_DeepSort_Pytorch#3]
你好，
Downloading https://pjreddie.com/media/files/yolov3-spp-ultralytics.pt

链接失效，能提供百度云链接的.pt文件吗，非常感谢

**Comment by mikel-brostrom** [comment]
Hi!
You should be downloading the yolov3-spp-ultralytics.pt weights from https://drive.google.com/open?id=1LezFG5g3BCW6iYaV89B2i64cqEUZD7e0 (not https://pjreddie.com/media/files/yolov3-spp-ultralytics.pt) and place them under yolov3/weights

**Comment by Angel0003** [comment]
> Hi!
> You should be downloading the yolov3-spp-ultralytics.pt weights from https://drive.google.com/open?id=1LezFG5g3BCW6iYaV89B2i64cqEUZD7e0 (not https://pjreddie.com/media/files/yolov3-spp-ultralytics.pt) and place them under yolov3/weights

thanks a lot！
