### ISSUE TITLE
Optimizing tracking script, a small change that can push tracking from lower fps to atleast 30 fps

### ISSUE THREAD

**Issue by OmkarShidore** [mikel-brostrom/Yolov3_DeepSort_Pytorch#5]
During inference there's a small mistake you've done or maybe you didn't notice it.
when you check the detected output of yolo that is 'det'. you update the tracker using a list. now the thing you've missed is you push xywh list again and again into the tracker because of the iteration. all you have to do is do this push the entire list once. I've attached an image so you'll understand. just move the indent of deepsort.update and the next if loop which consist of drawing bounding box. this will make updating tracker and drawing bounding box n (number of objects detected in frame) times faster.
![Screenshot 2020-09-26 171635](https://user-images.githubusercontent.com/35575009/94340020-0f420000-001c-11eb-86a8-aae850855929.jpg)

**Comment by mikel-brostrom** [comment]
Your are totally right @OmkarShidore! However, this repo won't get any new updates as I am
focusing on maintaining Yolov5_DeepSort_Pytorch. Moreover, this issue was solved in the Yolov5 version of this repo so I recommend you to switch to that one.
