### ISSUE TITLE
Link to yolov3 pytorch weights file cannot be accessed

### ISSUE THREAD

**Issue by nadinewijaya** [mikel-brostrom/Yolov3_DeepSort_Pytorch#8]
Hi, I was trying to use the trained weights on my own model and was unable to access the file from google drive.

I was wondering if this file could be made public again?

Thank you!

![image](https://user-images.githubusercontent.com/95895312/188417730-a81ecf09-1983-4553-80a0-9dcca35a1812.png)
![image](https://user-images.githubusercontent.com/95895312/188417649-1c7e281c-ce8f-4172-9244-ac8c08c50997.png)

**Comment by mikel-brostrom** [comment]
Yolov3 is a submodule and I have absolutely no control over the models. I recommend you to use
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet which is a humongous upgrade from this repo
